name: Test Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - run: |
          ./gradlew build
          if [ $? -ne 0 ]; then
            echo "Error: Gradle build failed."
            git reset --hard
            exit 1
          fi