name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Configurar JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Configurar Gradle
        uses: gradle/setup-gradle@v3

      - name: Compilar con Gradle Wrapper
        id: gradle_build
        run: |
          result=$(./gradlew build 2>&1)  # Ejecutar la compilación y capturar la salida
          echo "::set-output name=result::${result}"  # Almacenar el resultado en una variable de salida

      - name: Verificar resultado de la compilación
        if: steps.gradle_build.outputs.result != '0'  # Verificar si la compilación falló (resultado distinto de 0)
        run: |
          echo "Error: Gradle build failed."
          git checkout -- .  # Descartar cambios en el directorio de trabajo
          exit 1