name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle Wrapper
        id: gradle_build
        run: |
            result=$(./gradlew build 2>&1)  # Ejecutar la compilaci贸n y capturar la salida
            echo "::set-output name=result::${result}"  # Almacenar el resultado en una variable de salida

      - name: Verificar resultado de la compilaci贸n
        if: steps.gradle_build.outputs.result != '0'  # Verificar si la compilaci贸n fall贸 (resultado distinto de 0)
        run: |
          
          if [[ steps.gradle_build.outputs.result == 1 ]]; then
            echo "Error: Gradle build failed."
            git reset --hard $(git rev-parse HEAD~1)  # Revertir cambios locales
            exit 1
          fi
